### ISSUE TITLE
Не находит "рубля", "рублей", но находит "рубль", "рублем", "рублю"

### ISSUE THREAD

**Issue by cheebo** [imotov/elasticsearch-analysis-morphology#21]
Добрый день, 
столкнулся с такой проблемой:
Есть поле с названием search. В нем хранится строка на русском языке.
Конфиг такой для поля:

```
search:
  type: string
  analyzer: ru_analyzer

analyzer:
  ru_analyzer:
    type: custom
    tokenizer: standard
    filter: [lowercase, word_delimiter, russian_morphology, english_morphology, ru_stopwords]
filter:
  ru_stopwords:
    type: stop
    stopwords: '<пропущено>'
```

При поиске по полю так же использую ru_analyzer.

Запросы к эластику говорят, что для "рубля" и "рублей" генерируется токен "рубль", как и для "рублем", "рублю".
Когда ищу, то для запросов "рубля" и "рублей" не находится ничего, а для запросов "рублем", "рублю" находятся нужные документы. 
Если к "рубля" и "рублей" добавить что-то, например "рубля монета" или "рублей монета", то находятся нужные документы.
Но например, для "10 рубля" и "10 рублей" не находится ни один документ.

Пока не нашлось других слов, которые давали бы такой же результат.

Эта ошибка связана с плагином или она где-то в эластике?
